// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelShutdown() {
  return window['go']['main']['App']['CancelShutdown']();
}

export function ExecuteAction(arg1) {
  return window['go']['main']['App']['ExecuteAction'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}
