// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDiskWriteSpeed(arg1:number):Promise<number>;

export function GetProcesses():Promise<Array<main.Process>>;
