// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';

export function AutoDetectInterface():Promise<string>;

export function GetIOStatByMac(arg1:string):Promise<net.IOCountersStat>;

export function GetInterfaceByMac(arg1:string):Promise<net.InterfaceStat>;

export function GetInterfaceDownloadSpeed(arg1:string):Promise<number>;

export function GetInterfaces():Promise<Array<net.InterfaceStat>>;
